//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelperNovokuznetskaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HelperNovokuznetskaya()
        {
            this.Novokuznetskaya = new HashSet<Novokuznetskaya>();
        }
    
        public int IdHelperNovokuznetskaya { get; set; }
        public string FLMHelperNovokuznetskaya { get; set; }
        public string NumberPhoneHelperNovokuznetskaya { get; set; }
        public string EmailHelperNovokuznetskaya { get; set; }
        public string PositionHelperNovokuznetskaya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novokuznetskaya> Novokuznetskaya { get; set; }
    }
}
