//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novokuznetskaya
    {
        public int IdNovokuznetskaya { get; set; }
        public int IdStaffNovokuznetskaya { get; set; }
        public int IdHelperNovokuznetskaya { get; set; }
        public int IdSessionNovokuznetskaya { get; set; }
        public int NumberOfNachosNovokuznetskaya { get; set; }
        public int NumberOfCrispsNovokuznetskaya { get; set; }
        public int AmountOfColaNovokuznetskaya { get; set; }
        public int AmountOfFantaNovokuznetskaya { get; set; }
        public int AmountOfSweetPopcornNovokuznetskaya { get; set; }
        public int AmountOfSaltedPopcornNovokuznetskaya { get; set; }
        public int AmountOfCaramelPopcornNovokuznetskaya { get; set; }
        public int IdCleaning { get; set; }
    
        public virtual Cleaning Cleaning { get; set; }
        public virtual HelperNovokuznetskaya HelperNovokuznetskaya { get; set; }
        public virtual SessionNovokuznetskaya SessionNovokuznetskaya { get; set; }
        public virtual StaffNovokuznetskaya StaffNovokuznetskaya { get; set; }
    }
}
