//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paveletskaya
    {
        public int IdPaveletskaya { get; set; }
        public int IdStaffPaveletskaya { get; set; }
        public int IdHelperPaveletskaya { get; set; }
        public int IdSessionPaveletskaya { get; set; }
        public int NumberOfNachosPaveletskaya { get; set; }
        public int NumberOfCrispsPaveletskaya { get; set; }
        public int AmountOfColaPaveletskaya { get; set; }
        public int AmountOfFantaPaveletskaya { get; set; }
        public int AmountOfSweetPopcornPaveletskaya { get; set; }
        public int AmountOfSaltedPopcornPaveletskaya { get; set; }
        public int AmountOfCaramelPopcornPaveletskaya { get; set; }
        public int IdCleaning { get; set; }
    
        public virtual Cleaning Cleaning { get; set; }
        public virtual HelperPaveletskaya HelperPaveletskaya { get; set; }
        public virtual SessionPaveletskaya SessionPaveletskaya { get; set; }
        public virtual StaffPaveletskaya StaffPaveletskaya { get; set; }
    }
}
