//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSmolenskaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionSmolenskaya()
        {
            this.Smolenskaya = new HashSet<Smolenskaya>();
        }
    
        public int IdSessionSmolenskaya { get; set; }
        public string NameSessionSmolenskaya { get; set; }
        public string ARSeissionSmolenskaya { get; set; }
        public string TimeSessionSmolenskaya { get; set; }
        public byte[] ImageSessionSmolenskaya { get; set; }
        public System.DateTime DateSessionSmolenskaya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smolenskaya> Smolenskaya { get; set; }
    }
}
