//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionPaveletskaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionPaveletskaya()
        {
            this.Paveletskaya = new HashSet<Paveletskaya>();
        }
    
        public int IdSessionPaveletskaya { get; set; }
        public string NameSessionPaveletskaya { get; set; }
        public string ARSeissionPaveletskaya { get; set; }
        public string TimeSessionPaveletskaya { get; set; }
        public byte[] ImageSessionPaveletskaya { get; set; }
        public System.DateTime DateSession { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paveletskaya> Paveletskaya { get; set; }
    }
}
