//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSmolenskaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffSmolenskaya()
        {
            this.Smolenskaya = new HashSet<Smolenskaya>();
        }
    
        public int IdStaffSmolenskaya { get; set; }
        public string FLMStaffSmolenskaya { get; set; }
        public string NumberPhoneStaffSmolenskaya { get; set; }
        public string EmailStaffSmolenskaya { get; set; }
        public string PositionStaffSmolenskaya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Smolenskaya> Smolenskaya { get; set; }
    }
}
