//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovayaYaroshevski.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffNovokuznetskaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffNovokuznetskaya()
        {
            this.Novokuznetskaya = new HashSet<Novokuznetskaya>();
        }
    
        public int IdStaffNovokuznetskaya { get; set; }
        public string FLMStaffNovokuznetskaya { get; set; }
        public string NumberPhoneStaffNovokuznetskaya { get; set; }
        public string EmailStaffNovokuznetskaya { get; set; }
        public string PositionStaffNovokuznetskaya { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novokuznetskaya> Novokuznetskaya { get; set; }
    }
}
